name: Base
logging: True
data_path: /data
unlabeled: True

model:
    pretrained: False
    projector_dim: 8_192

param:
    lr: 1e-4
    batch_size: 1_024

mixstyle:
    p: 1.0 
    alpha: 0.1
    eps: 1e-6

trainer:
    max_steps: 50_000
    check_val_every_n_epoch: 1

logger:
    project: pretraining-base