name: Base
logging: True
data_path: /data

data:
    name: camelyon
    path: /data

model:
    pretrained: False
    projector_dim: 8_192

param:
    lr: 1e-4
    batch_size: 1_024

disc:
    alpha: 1.0
    mult: 10.0

mixstyle:
    # TODO: implement
    active: False
    p: 1.0 
    alpha: 0.1
    eps: 1e-6

trainer:
    max_steps: 150_000
    check_val_every_n_epoch: 1
    warmup: 1_000

logger:
    project: pretraining-base