name: Debug
logging: False
max_epochs: 1
data_path: ../data
unlabeled: False
param:
    lr: 5e-4
    batch_size: 2
    projector_dim: 128
disc:
    alpha: 1.0
weights: scratch # TODO: use in train.py
dataset:
    name: iwildcam
    version: 1.0