defaults:
  - base

name: DomainNet
logging: False
unlabeled: False

data:
    name: domainnet
    num_workers: 4

model:
    pretrained: False
    projector_dim: 1_024

param:
    lr: 1e-4
    batch_size: 32

trainer:
    cos_decay: True
    warmup: 10_000

logger:
    project: pretraining-domainnet