name: Debug
logging: False
data_path: /data
unlabeled: False

data:
    name: domainnet
    path: /data

model:
    pretrained: False
    projector_dim: 128

param:
    lr: 1e-4
    batch_size: 128

disc:
    alpha: 0.0
    mult: 0.0

trainer:
    max_steps: 50_000
    check_val_every_n_epoch: 1
