name: Debug
logging: false
data_path: /data
unlabeled: false

data:
    name: camelyon
    path: /data
    num_classes: 2

    color_aug_fct: 1.0

model:
    pretrained: False
    projector_dim: 128

param:
    lr: 1e-4
    batch_size: 128

disc:
    alpha: 0.0
    mult: 0.0

mixstyle:
    active: false

trainer:
    max_steps: 50_000
    max_epochs: 1000
    check_val_every_n_epoch: 1
    warmup_epochs: 10
