defaults:
  - base

name: DomainNet
logging: True
unlabeled: False

data:
    name: domainnet
    num_workers: 16
    img_size: 128

model:
    pretrained: True
    projector_dim: 8_192

head_pretrain:
    active: True
    lr: 1e-4

param:
    lr: 5e-4
    batch_size: 1024

trainer:
    max_epochs: 1_000
    check_val_every_n_epoch: 10
    cos_decay: True

mixstyle:
    p: 0.0

logger:
    project: pretraining-domainnet-head