defaults:
  - base

name: DomainNet
logging: True
unlabeled: False

data:
    name: domainnet
    num_workers: 4

model:
    pretrained: True
    projector_dim: 4_096

param:
    lr: 5e-4
    batch_size: 256

trainer:
    max_steps: 500_000
    check_val_every_n_epoch: 3
    cos_decay: True
    # warmup: 5_000

mixstyle:
    p: 0.0

logger:
    project: pretraining-domainnet