defaults:
  - base

logging: True

data_path: /home/yasin/notebooks/data
unlabeled: False

model:
    pretrained: True
    projector_dim: 1_024

param:
    lr: 1e-4
    batch_size: 128

disc:
    alpha: 0.0
    mult: 0.0

logger:
    project: pretraining-pacs