defaults:
  - base

data_path: /tmp
logging: True
unlabeled: False

model:
    pretrained: True
    projector_dim: 1_024

param:
    lr: 1e-4
    batch_size: 128

disc:
    alpha: 0.0
    mult: 0.0

trainer:
    max_steps: 10_000

logger:
    project: pretraining-pacs