defaults:
  - base

data_path: /tmp
logging: True
unlabeled: False

data:
    name: pacs
    path: /tmp

model:
    pretrained: True
    projector_dim: 1_024

param:
    lr: 1e-4
    batch_size: 128

trainer:
    max_steps: 10_000
    check_val_every_n_epoch: 1

trainer:
    max_steps: 10_000

logger:
    project: pretraining-pacs