defaults:
  - base

data_path: /data
logging: True
unlabeled: False

model:
    pretrained: True
    projector_dim: 1_024

param:
    lr: 0.0 # 1e-4
    batch_size: 32

trainer:
    max_steps: 10_000
    check_val_every_n_epoch: 1

logger:
    project: pretraining-pacs