_BASE_: configs/base.yaml

name: PACS Baseline

data:
  name: pacs
  path: /data
  unlabeled: false
  color_aug: true

param:
  batch_size: 128
  lr: 1e-4

model:
  pretrained: true
  projector_dim: 1024

mixstyle:
  p: 0.0
  alpha: 0.1
  eps: 1e-6

disc:
  alpha: 0.0
  mult: 10

trainer:
  max_steps: 11000
  check_val_every_n_epoch: 1
  warmup: 1000

logger:
  project: pretraining_final_pacs