_BASE_: configs/base.yaml

name: Camelyon Baseline

data:
  name: camelyon
  path: /data
  unlabeled: true 
  color_aug: true

param:
  batch_size: 1024
  lr: 1e-4

model:
  pretrained: false
  projector_dim: 8192

mixstyle:
  p: 0.0
  alpha: 0.1
  eps: 1e-6

disc:
  alpha: 0.0
  mult: 10

trainer:
  max_steps: 150000
  check_val_every_n_epoch: 1
  warmup: 1000

logger:
  project: pretraining_final_camelyon